apiVersion: apps/v1
kind: Deployment
metadata:
  name: Angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Angular-app
  template:
    metadata:
      labels:
        app: Angular-app
    spec:
      imagePullSecrets:
      - name: masterkey
      containers:
      - name: Angular-app
        image: master:9001/angular:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Angular-service
spec:
  type: NodePort
  selector:
    app: Angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32001